### ISSUE TITLE
Use AsyncLocalStorage if available

### ISSUE THREAD

**Issue by mcollina** [thorough-developer/fastify-http-context#5]
https://nodejs.org/dist/latest-v14.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage provides a very similar experience of cls-hooked at a fraction of the overhead. It should use that instead when/if available.

**Comment by thorough-developer** [comment]
@mcollina Good call! I will look into implementing this asap!

**Comment by thorough-developer** [comment]
@mcollina Am I waiting on this PR: https://github.com/nodejs/node/pull/32318 ? for a backport to 12?

**Comment by thorough-developer** [comment]
Got this implemented. I see a 33% increase in performance on average which is pretty amazing. Just waiting on the backport: https://github.com/thorough-developer/fastify-http-context/tree/async-local-storage

**Comment by mcollina** [comment]
I know :). I was part of the team that came up with the theory that makes it possible to be faster.

**Comment by thorough-developer** [comment]
Done https://github.com/thorough-developer/fastify-http-context/pull/6

Added a conditional to handle whether the class was available. So 13+ and hopefully 12 soon will get the performance boost. Thanks for the suggestion
